data:
  name: simple_10000
  noise: noise_10000
  SNR: 5
  frequency_lower: 40
  frequency_upper: 2048
  bandpass_lower: 128
  bandpass_upper: 2048
  whitening_segment_duration: 0.5
  whitening_max_filter_duration: 0.5

training:
  batch_size: 16
  nb_workers: 2
  nb_epochs: 5
  device: cpu:0

model:
  loss: VMF # The options for the loss functions are: 'VMF' or 'Kent'

test_name: test_simple_5000